### NumPy

### Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
print('Hello')

Hello


In [24]:
import numpy as np

In [25]:
a = np.array([1, 2, 3])

print(a)

[1 2 3]


In [26]:
import pickle

In [27]:
import pandas

In [28]:
import pandas as pd

In [30]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]).transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [31]:
mean_a = a.mean(axis=0)
print(mean_a)

[2.  8.4]


### Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [33]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [34]:
 a_centered[0]

array([-1. , -2.4])

In [35]:
a_centered[0]

array([-1. , -2.4])

### Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [36]:
a_centered = a_centered.T[0] @ a_centered.T[1]

In [37]:
print(a_centered)

8.0


### Тема “Работа с данными в Pandas”

### Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [38]:
import pandas

In [39]:
import pandas as pd

In [42]:
authors = pd.DataFrame({'author_id':[1, 2, 3], 
                      'author_name':['Тургенев', 'Чехов', 'Островский']}, 
                      columns=['author_id', 'author_name'])

In [43]:
print(authors)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский


In [44]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                    'book_title':['Отцы и деты', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'price':[450, 300, 350, 500, 450, 370, 290]},
                   columns=['author_id', 'book_title', 'price'])

In [45]:
print(book)

   author_id            book_title  price
0          1           Отцы и деты    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290


### Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [48]:
df_authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')

In [53]:
print(df_authors_price)

   author_id author_name            book_title  price
0          1    Тургенев           Отцы и деты    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290


### Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [54]:
top5 = df_authors_price.nlargest(5, 'price')

In [55]:
print(top5)

   author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и деты    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350
